# Generated by Django 4.0.4 on 2022-05-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='stock',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='logistic.stock'),
        ),
    ]
